steps:
  - name: 'gcr.io/cloud-builders/mvn:appengine'
    id: 'Generate Maven settings file'
    entrypoint: 'bash'
    args: [
        '-c',
        'echo "
        <settings>
          <servers>
            <server>
              $$GCP_MVN_REPO_SERVER
            </server>
          </servers>
          <mirrors>
            <mirror>
              $$GCP_MVN_REPO_MIRROR
            </mirror>
          </mirrors>
        </settings>" > /workspace/settings.xml'
    ]
    secretEnv: ['GCP_MVN_REPO_SERVER','GCP_MVN_REPO_MIRROR']

  - name: 'gcr.io/cloud-builders/mvn:appengine'
    id: 'Generate GAE version name'
    entrypoint: 'bash'
    args: [
        '-c',
        'echo build-$(echo $BUILD_ID | cut -d"-" -f 1) > /workspace/version
      && echo VERSION NAME = $(cat /workspace/version)'
    ]

  - name: 'gcr.io/cloud-builders/mvn:appengine'
    id: 'Application deployment'
    entrypoint: 'bash'
    args: [
        '-c',
        'mvn clean package appengine:deploy --settings /workspace/settings.xml -Dbbva.environment=${_BBVA_GAE_ENV} -Dmaven.test.skip=true -Dapp.deploy.promote=false -Dappengine.deploy.version=$(cat /workspace/version)'
    ]

availableSecrets:
  secretManager:
    - versionName: projects/${_GCP_MVN_REPO_SERVER_PROJECT}/secrets/${_GCP_MVN_REPO_SERVER_SECRET_NAME}/versions/${_GCP_MVN_REPO_SERVER_VERSION}
      env: 'GCP_MVN_REPO_SERVER'
    - versionName: projects/${_GCP_MVN_REPO_MIRROR_PROJECT}/secrets/${_GCP_MVN_REPO_MIRROR_SECRET_NAME}/versions/${_GCP_MVN_REPO_MIRROR_VERSION}
      env: 'GCP_MVN_REPO_MIRROR'

substitutions:
  _GCP_MVN_REPO_SERVER_SECRET_NAME: 'gcp-global-mvn-repository-server-vdc'
  _GCP_MVN_REPO_SERVER_VERSION: 'latest'
  _GCP_MVN_REPO_SERVER_PROJECT: 'bbva-devtools-gcp'
  _GCP_MVN_REPO_MIRROR_SECRET_NAME: 'gcp-global-mvn-repository-mirror-vdc'
  _GCP_MVN_REPO_MIRROR_VERSION: 'latest'
  _GCP_MVN_REPO_MIRROR_PROJECT: 'bbva-devtools-gcp'

logsBucket: 'gs://$PROJECT_ID-cloudbuild-logs'
timeout: "1200s"