steps:
  - name: 'docker:19.03'
    id: 'Artifactory Registry authentication'
    entrypoint: '/bin/sh'
    args: ['-c', 'docker login -u=$$BOT_GCP_READER_USER -p=$$BOT_GCP_READER_PASSWORD artifactory.globaldevtools.bbva.com']
    secretEnv: ['BOT_GCP_READER_USER', 'BOT_GCP_READER_PASSWORD']

  - name: 'artifactory.globaldevtools.bbva.com/gl-gcp-docker-local/gcp/arch/bbva-fga-cli-ng:latest'
    id: 'Application deployment cli'
    entrypoint: 'bash'
    args: [ '-c','fga-cli.py deploy all --env=${_BBVA_GAE_ENV} -- -Dmaven.test.skip=true -Dapp.deploy.promote=false']
    env:
      - 'CLI_MODE=cloud_build'
      - 'MAVEN_OPTS=-Duser.home=/builder/home'
    secretEnv: ['BOT_GCP_READER_USER','BOT_GCP_READER_PASSWORD']

availableSecrets:
  secretManager:
    - versionName: projects/${_GCP_SM_PROJECT}/secrets/${_GCP_VDC_READER_USER}/versions/${_GCP_VDC_READER_USER_VERSION}
      env: 'BOT_GCP_READER_USER'
    - versionName: projects/${_GCP_SM_PROJECT}/secrets/${_GCP_VDC_READER_PASS}/versions/${_GCP_VDC_READER_PASS_VERSION}
      env: 'BOT_GCP_READER_PASSWORD'

substitutions:
  _GCP_VDC_READER_USER: 'bot-gcp-reader-vdc-username'
  _GCP_VDC_READER_USER_VERSION: 'latest'
  _GCP_VDC_READER_PASS: 'bot-gcp-reader-vdc-password'
  _GCP_VDC_READER_PASS_VERSION: 'latest'
  _GCP_SM_PROJECT: 'bbva-devtools-gcp'

logsBucket: 'gs://$PROJECT_ID-cloudbuild-logs'
timeout: "1200s"