runtime: java17
service: default
instance_class: F4

automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1
  max_instances: 2
  max_concurrent_requests: 40

handlers:
  - url: /tasks/.*
    script: auto
    secure: always
    login: admin
  - url: .*
    script: auto
    secure: always

inbound_services:
  - warmup

env_variables:
  PORT: 8080
  APP_PROPERTIES_FILES: common.properties, application.properties

entrypoint: 'java -jar webapp.jar'